name: Build and Push Base Windows C++ Image

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Adjust if necessary
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
            
      - name: Build Base Docker Image
        run: |
          docker build --no-cache --tag saidursajol/my-base-windows-cpp-image:1.0 .

      - name: Push Base Docker Image
        run: docker push saidursajol/my-base-windows-cpp-image:1.0
